### ISSUE TITLE
Proposal Feedback

### ISSUE THREAD

**Issue by munirsidd** [arionct/Boston-City-Budget#2]
Hi, 

I think your proposal looks good! One thing to note is that the link for Boston's operating budget dataset is incorrect - it links to a PDF instead of the actual dataset. Moreover, you should consider specifying which datasets you would use to get geographic and demographic data.

**Comment by Rehan164** [comment]
Our operating budget link to dataset is https://github.com/arionct/Boston-City-Budget/blob/main/data/operating_budget.csv. That is what we are using for our data.
